title = "liamdalg"
baseURL = 'https://liamdalg.co.uk/'

# This is what goes in <html lang="">
locale = 'en-gb'

# This defines how dates are formatted
defaultContentLanguage = "en-gb"

# Preserve tag/section casing as written instead of Hugo's default AP-style title-casing
titleCaseStyle = "none"

# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
[markup.highlight]
noClasses = false
lineNos = true
lineNumbersInTable = false
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20
[[menu.main]]
pageRef = "about"
name = 'About'
url = '/about/'
weight = 30

[params]
description = "liamdalg - Personal lazy blog"
mainSections = ['posts']

[params.author]
intro = "liamdalg"
name = "Liam"
description = "Pencil-pusher with the pencil-pusher blues."

[[params.socialIcons]]
name = "github"
url = "https://github.com/liamdalg"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/liamdalg"
